CREATE TABLE users (id INTEGER PRIMARY KEY, email VARCHAR(320) NOT NULL UNIQUE, password_hash VARCHAR(255) NOT NULL, role VARCHAR(20) NOT NULL DEFAULT 'customer', created_at DATETIME NOT NULL);
CREATE TABLE products (id INTEGER PRIMARY KEY, sku VARCHAR(80) NOT NULL UNIQUE, slug VARCHAR(120) NOT NULL UNIQUE, name VARCHAR(200) NOT NULL, description TEXT NOT NULL, price_cad NUMERIC NOT NULL, stock INTEGER NOT NULL DEFAULT 0, purity VARCHAR(80), lot VARCHAR(80), coa_url VARCHAR(500), featured BOOLEAN NOT NULL DEFAULT 0, active BOOLEAN NOT NULL DEFAULT 1);
CREATE TABLE affiliates (id INTEGER PRIMARY KEY, user_id INTEGER REFERENCES users(id), code VARCHAR(40) NOT NULL UNIQUE, commission_rate NUMERIC NOT NULL DEFAULT 0.10, payout_currency VARCHAR(20), payout_address VARCHAR(180), active BOOLEAN NOT NULL DEFAULT 1);
CREATE TABLE orders (id INTEGER PRIMARY KEY, order_number VARCHAR(40) NOT NULL UNIQUE, user_id INTEGER REFERENCES users(id), email VARCHAR(320) NOT NULL, status VARCHAR(30) NOT NULL DEFAULT 'pending', payment_provider VARCHAR(40) NOT NULL, payment_reference VARCHAR(120), subtotal_cad NUMERIC NOT NULL, shipping_cad NUMERIC NOT NULL, total_cad NUMERIC NOT NULL, affiliate_id INTEGER REFERENCES affiliates(id), created_at DATETIME NOT NULL);
CREATE TABLE order_items (id INTEGER PRIMARY KEY, order_id INTEGER NOT NULL REFERENCES orders(id), product_id INTEGER NOT NULL REFERENCES products(id), sku VARCHAR(80) NOT NULL, name VARCHAR(200) NOT NULL, quantity INTEGER NOT NULL, unit_price_cad NUMERIC NOT NULL);
CREATE TABLE affiliate_clicks (id INTEGER PRIMARY KEY, affiliate_id INTEGER NOT NULL REFERENCES affiliates(id), referrer VARCHAR(300), landing_path VARCHAR(300), created_at DATETIME NOT NULL);
CREATE TABLE commissions (id INTEGER PRIMARY KEY, affiliate_id INTEGER NOT NULL REFERENCES affiliates(id), order_id INTEGER NOT NULL UNIQUE REFERENCES orders(id), amount_cad NUMERIC NOT NULL, status VARCHAR(30) NOT NULL DEFAULT 'pending', payout_id INTEGER REFERENCES payouts(id));
CREATE TABLE payouts (id INTEGER PRIMARY KEY, affiliate_id INTEGER NOT NULL REFERENCES affiliates(id), period VARCHAR(7) NOT NULL, amount_cad NUMERIC NOT NULL, status VARCHAR(30) NOT NULL DEFAULT 'ready', admin_note TEXT, UNIQUE (affiliate_id, period));
CREATE TABLE webhook_events (id INTEGER PRIMARY KEY, provider VARCHAR(40) NOT NULL, event_id VARCHAR(160) NOT NULL, created_at DATETIME NOT NULL, UNIQUE (provider, event_id));
